---

- name: 'Test playbook to read the content from a file'
  hosts: all
  gather_facts: false

  tasks:

    - name: "Get {{ filepath }} content"
      command: "cat {{ filepath }}"
      register: cnt

    - name: "Check if {{ filepath }} content is correct"
      lineinfile:
        dest: "{{ filepath }}"
        line: "{{ cnt_to_check }}"
      check_mode: yes
      register: present
      failed_when: present.changed